const roomsData = [
  {
    id: 1,
    name: "Пом. 1",
    type: "Класс",
    area: 54.6,
    socketGroup: "Гр.Р3-1",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "75 м",
    socketProtection: "АД32 С16, 30мА, 1Р+N",
    lightGroup: "Гр.О3-3",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "1,29 кВт (совм. с 2,3,4)",
    lightLength: "120 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (1×30Вт)",
    lightProtection: "ВА47-63 С10",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (6 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Выключатель одноклавишный скрытый 10А EKF EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный скрытый 10А EKF EWV10-023-10 (1 шт.)",
      "Светильник BEST OFFICE CLASS 30 IP40 1×30Вт (15 шт.)",
      "Светильник для доски BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Кабель канал 3м",
      "Распред коробка 19шт",
      "Штроба 20м",
      "Проходные отверстия с гильзами (диаметр до 25 мм) - 2 шт."
    ],
    note: "⚠️ Высота розеток/выключателей: 1,8 м от ч.п.",
    hasSchemes: true,
    schemes: {
      lighting: "images/pom1-lighting.png",
      sockets: "images/pom1-sockets.png"
    }
  },
   {
    id: 2,
    name: "Пом. 2",
    type: "Класс",
    area: 18.1,
    socketGroup: "Гр.Р3-1",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "85 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-3 (совм.)",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (3 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (2 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (3 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (1 шт.)",
      "Штроба 10м",
      "Распред коробка 5шт",
      "Отверстие проходное с гильзами (диаметр до 25 мм) - 2 шт."
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom2-lighting.png",
      sockets: "images/pom2-sockets.png"
    }
  },
  {
    id: 3,
    name: "Пом. 3",
    type: "Класс",
    area: 74.3,
    socketGroup: "Гр.Р3-2",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "71 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-3",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (18 шт.)",
    equipment: [
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 IP40 (18 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40, для освещения досок BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-023-10 (1 шт.)",
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (3 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Кабель канал (3 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)",
      "Штроба (27 м)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom3-lighting.png",
      sockets: "images/pom3-sockets.png"
    }
  },
    {
    id: 4,
    name: "Пом. 4",
    type: "Класс",
    area: 17.2,
    socketGroup: "Гр.Р3-2",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "88 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-3",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (3 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (2 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (3 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (1 шт.)",
      "Распред коробка (5 шт.)",
      "Штроба (8 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom4-lighting.png",
      sockets: "images/pom4-sockets.png"
    }
  },
   {
    id: 5,
    name: "Пом. 5",
    type: "Класс",
    area: 62.3,
    socketGroup: "Гр.Р3-3",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "93 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-4",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "1,02 кВт (совм. с 6)",
    lightLength: "135 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (15 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (4 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (15 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40, для освещения досок BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-023-10 (1 шт.)",
      "Кабель канал (3 м)",
      "Распред коробка (22 шт.)",
      "Штроба (24 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom5-lighting.png",
      sockets: "images/pom5-sockets.png"
    }
  },
 {
    id: 6,
    name: "Пом. 6",
    type: "Класс",
    area: 56.4,
    socketGroup: "Гр.Р3-4",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "90 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-4",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (15 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (4 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (15 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40, для освещения досок BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-023-10 (1 шт.)",
      "Кабель канал (3 м)",
      "Распред коробка (23 шт.)",
      "Штроба (26 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom6-lighting.png",
      sockets: "images/pom6-sockets.png"
    }
  },
  {
    id: 7,
    name: "Пом. 7",
    type: "Класс",
    area: 53.3,
    socketGroup: "Гр.Р3-5",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "79 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-5",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "1,20 кВт (совм. с 8,9)",
    lightLength: "154 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (15 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (5 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (15 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40, для освещения досок BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-023-10 (1 шт.)",
      "Кабель канал (3 м)",
      "Распред коробка (22 шт.)",
      "Штроба (22 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom7-lighting.png",
      sockets: "images/pom7-sockets.png"
    }
  },
  {
    id: 8,
    name: "Пом. 8",
    type: "Класс",
    area: 72.6,
    socketGroup: "Гр.Р3-6",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "77 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-5",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (18 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (3 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (18 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40, для освещения досок BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-023-10 (1 шт.)",
      "Кабель канал (3 м)",
      "Распред коробка (25 шт.)",
      "Штроба (37 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom8-lighting.png",
      sockets: "images/pom8-sockets.png"
    }
  },
   {
    id: 9,
    name: "Пом. 9",
    type: "Класс",
    area: 17.9,
    socketGroup: "Гр.Р3-6",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "77 м (ответвление)",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-5",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (3 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (2 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (3 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А (1 шт.)",
      "Распред коробка (5 шт.)",
      "Штроба (10 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom9-lighting.png",
      sockets: "images/pom9-sockets.png"
    }
  },
  {
    id: 10,
    name: "Пом. 10",
    type: "Класс",
    area: 73.2,
    socketGroup: "Гр.Р3-7",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "35 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-6",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "0,72 кВт (совм. с 11)",
    lightLength: "85 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (18 шт.) + BEST ССП PL-03 (2 шт.)",
    equipment: [
      "Розетка встроенная 2-местная с/з 16А (IP20) EKF Валенсия EWR16-128-10 (3 шт.)",
      "Розетка накладная 1-местная с/з 16А (IP20) EKF Минск EGR16-028-10 (1 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40 BEST OFFICE CLASS 30 (18 шт.)",
      "Светильник светодиодный, 1х30Вт, IP40, для освещения досок BEST ССП PL-03 CLASS 30 (2 шт.)",
      "Выключатель одноклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-021-10 (2 шт.)",
      "Выключатель двухклавишный для скрытой установки, IP20, 10А EKF Валенсия EWV10-023-10 (1 шт.)",
      "Кабель канал (3 м)",
      "Проходные отверстия с гильзами диаметр до 25 мм (2 шт.)",
      "Распред коробка (25 шт.)",
      "Штроба (38 м)"
    ],
    hasSchemes: true,
    schemes: {
      lighting: "images/pom10-lighting.png",
      sockets: "images/pom10-sockets.png"
    }
  },
  {
    id: 11,
    name: "Пом. 11",
    type: "Класс",
    area: 17.8,
    socketGroup: "Гр.Р3-7",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "31 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-6",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~2 шт.)",
    equipment: "Розетки 2-местные IP20 (~2 шт.), выключатель 1-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 12,
    name: "Пом. 12",
    type: "Лест. клетка",
    area: 16.7,
    lightGroup: "Гр.О3-11",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (накладные, 1×10Вт) (2 шт.)",
    lightProtection: "ВА47-63 С10",
    equipment: "Выключатель открытый IP44, 10А. Прокладка в кабель-канале/штробе.",
    hasSchemes: false,
    borderColor: "var(--lit)"
  },
  {
    id: 13,
    name: "Пом. 13",
    type: "Класс",
    area: 20.2,
    socketGroup: "Гр.Р3-8",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,5 кВт (повыш.)",
    socketLength: "45 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-7",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "0,84 кВт (совм. с 14,15)",
    lightLength: "86 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40",
    equipment: "Розетки 2-местные IP20 (~2 шт.), выключатель 1-кл. скрытый, светильники IP40 (~2 шт.)",
    hasSchemes: false
  },
  {
    id: 14,
    name: "Пом. 14",
    type: "Класс",
    area: 72.4,
    socketGroup: "Гр.Р3-8",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,5 кВт",
    socketLength: "61 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-7",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~5 шт.)",
    equipment: "Розетки 2-местные IP20 (~5 шт.), выключатель 2-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 15,
    name: "Пом. 15",
    type: "Класс",
    area: 17.6,
    socketGroup: "Гр.Р3-8 (резерв/ответвление)",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    lightGroup: "Гр.О3-7",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~2 шт.)",
    equipment: "Розетки 2-местные IP20 (~2 шт.), выключатель 1-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 16,
    name: "Пом. 16",
    type: "Лест. клетка",
    area: 17.0,
    lightGroup: "Гр.О3-11 (совм. с другими вспом.)",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (2 шт.)",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    equipment: "Выключатель открытый IP44. Эвакуационный путь.",
    hasSchemes: false,
    borderColor: "var(--lit)"
  },
  {
    id: 17,
    name: "Пом. 17",
    type: "Класс",
    area: 55.3,
    socketGroup: "Гр.Р3-9",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "35 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-1",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "1,02 кВт (совм. с 18)",
    lightLength: "50 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40",
    equipment: "Розетки 2-местные IP20 (~4 шт.), выключатель 1-кл. скрытый, светильники IP40 (~4 шт.)",
    hasSchemes: false
  },
  {
    id: 18,
    name: "Пом. 18",
    type: "Класс",
    area: 55.3,
    socketGroup: "Гр.Р3-10",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "31 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-1",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~4 шт.)",
    equipment: "Розетки 2-местные IP20 (~4 шт.), выключатель 1-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 19,
    name: "Пом. 19",
    type: "Класс",
    area: 54.2,
    socketGroup: "Гр.Р3-11",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "45 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-2",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "1,11 кВт (совм. с 20)",
    lightLength: "70 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40",
    equipment: "Розетки 2-местные IP20 (~4 шт.), выключатель 2-кл. скрытый, светильники IP40 (~4 шт.)",
    hasSchemes: false
  },
  {
    id: 20,
    name: "Пом. 20",
    type: "Класс",
    area: 61.0,
    socketGroup: "Гр.Р3-12",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "61 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-2",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~5 шт.)",
    equipment: "Розетки 2-местные IP20 (~4 шт.), выключатель 1-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 21,
    name: "Пом. 21",
    type: "Коридор",
    area: 197.8,
    lightGroup: "Гр.О3-9",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "0,51 кВт",
    lightLength: "70 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~8 шт.)",
    lightProtection: "ВА47-63 С10",
    emergencyLightGroup: "Гр.АО3-1",
    emergencyLightCable: "ВВГнг(А)-FRLSLTx 4×1,5",
    emergencyLightLength: "75 м",
    emergencyLightProtection: "ВА47-63 С10",
    emergencyNote: "Светильники со встроенным БАП (3 шт.)",
    equipment: "Выключатели 1-кл. скрытые. Расстояние рабочего/аварийного кабеля ≥20 мм.",
    note: "🔋 Между БАП и лампами запрещена установка коммутационных аппаратов.",
    hasSchemes: false,
    borderColor: "var(--emr)"
  },
  {
    id: 22,
    name: "Пом. 22",
    type: "Класс",
    area: 23.2,
    socketGroup: "Гр.Р3-13",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "33 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-8",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "0,60 кВт (совм. с 23,24)",
    lightLength: "65 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40",
    equipment: "Розетки 2-местные IP20 (~2 шт.), выключатель 1-кл. скрытый, светильники IP40 (~2 шт.)",
    hasSchemes: false
  },
  {
    id: 23,
    name: "Пом. 23",
    type: "Класс",
    area: 25.4,
    socketGroup: "Гр.Р3-14",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "43 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-8",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~2 шт.)",
    equipment: "Розетки 2-местные IP20 (~2 шт.), выключатель 1-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 24,
    name: "Пом. 24",
    type: "Класс",
    area: 24.3,
    socketGroup: "Гр.Р3-15",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "1,0 кВт",
    socketLength: "45 м",
    socketProtection: "АД32 С16, 30мА",
    lightGroup: "Гр.О3-8",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~2 шт.)",
    equipment: "Розетки 2-местные IP20 (~2 шт.), выключатель 1-кл. скрытый",
    hasSchemes: false
  },
  {
    id: 25,
    name: "Пом. 25",
    type: "Коридор",
    area: 196.5,
    lightGroup: "Гр.О3-10",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightPower: "0,51 кВт",
    lightLength: "92 м",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~8 шт.)",
    emergencyLightGroup: "Гр.АО3-2",
    emergencyLightCable: "ВВГнг(А)-FRLSLTx 4×1,5",
    emergencyLightLength: "80 м",
    emergencyLightProtection: "ВА47-63 С10",
    emergencyNote: "Светильники со встроенным БАП (3 шт.)",
    equipment: "Выключатели скрытые. Эвакуационный путь. Огнестойкий кабель.",
    hasSchemes: false,
    borderColor: "var(--emr)"
  },
  {
    id: 26,
    name: "Пом. 26",
    type: "Сан. узел",
    area: 11.5,
    lightGroup: "Гр.О3-11 (совм. 26-35)",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (накладные, 1×10Вт) (1 шт.)",
    lightHeight: "2,7 м от ч.п.",
    equipment: "Выключатель вынесен наружу (1,8 м). IP65 обязательно.",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 27,
    name: "Пом. 27",
    type: "Сан. узел",
    area: 13.2,
    socketGroup: "Гр.Р3-17",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "3,0 кВт",
    socketLength: "46 м",
    socketType: "1-местная IP44 с крышкой (1 шт.)",
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт., h=2,7м)",
    note: "⚠️ Влажное помещение. Выключатель снаружи. IP44/IP65.",
    hasSchemes: false,
    borderColor: "var(--pow)"
  },
  {
    id: 28,
    name: "Пом. 28",
    type: "Сан. узел",
    area: 6.8,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    equipment: "Выключатель вынесен наружу. Прокладка в ПВХ-трубе.",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 29,
    name: "Пом. 29",
    type: "Сан. узел",
    area: 6.4,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 30,
    name: "Пом. 30",
    type: "Сан. узел",
    area: 1.3,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 31,
    name: "Пом. 31",
    type: "Сан. узел",
    area: 3.5,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 32,
    name: "Пом. 32",
    type: "Сан. узел",
    area: 1.7,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 33,
    name: "Пом. 33",
    type: "Кладовая",
    area: 1.7,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    equipment: "⚠️ Выключатель установить в запирающий шкафчик с возможностью опломбирования.",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 34,
    name: "Пом. 34",
    type: "Сан. узел",
    area: 13.4,
    socketGroup: "Гр.Р3-16",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "3,0 кВт",
    socketLength: "33 м",
    socketType: "1-местная IP44 с крышкой (1 шт.)",
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт., h=2,7м)",
    note: "⚠️ Влажное помещение. Выключатель снаружи.",
    hasSchemes: false,
    borderColor: "var(--pow)"
  },
  {
    id: 35,
    name: "Пом. 35",
    type: "Сан. узел",
    area: 10.9,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 36,
    name: "Пом. 36",
    type: "Сан. узел",
    area: 6.8,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 37,
    name: "Пом. 37",
    type: "Сан. узел",
    area: 1.7,
    lightGroup: "Гр.О3-11",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 38,
    name: "Пом. 38",
    type: "Площадка",
    area: 364.0,
    lightGroup: "Гр.О3-11 / резерв ЩО3",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 + ЖКХ-С 10 IP65 (~15 шт.)",
    equipment: "Розетки накладные IP20 для уборочной техники (2 шт., h=0,3-1,0м). Эвакуационные указатели.",
    hasSchemes: false
  },
  {
    id: 39,
    name: "Пом. 39",
    type: "Лест. клетка",
    area: 17.9,
    lightGroup: "Гр.О3-11 (совм.)",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (2 шт.)",
    equipment: "Выключатель открытый IP44. Эвакуационный путь.",
    hasSchemes: false,
    borderColor: "var(--lit)"
  },
  {
    id: 40,
    name: "Пом. 40",
    type: "Актовый зал",
    area: 169.0,
    lightPower: "Через резерв/смежные щиты (уточняется по актуализации)",
    lightFixtures: "BEST OFFICE CLASS 30 IP40 (~10 шт.)",
    note: "📐 Точная разводка уточняется на месте. Нормы освещённости 200-300 лк.",
    hasSchemes: false
  },
  {
    id: 41,
    name: "Пом. 41",
    type: "Склад",
    area: 3.6,
    socketGroup: "Гр.Р2-4-5 (с 2 этажа)",
    socketCable: "ВВГнг(А)-LSLTx 3×2,5",
    socketPower: "0,5 кВт",
    socketLength: "28 м",
    lightGroup: "Гр.О2-2-8",
    lightCable: "ВВГнг(А)-LSLTx 3×1,5",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    equipment: "Розетка накладная IP20 (h=0,3-1,0м). Выключатель скрытый.",
    hasSchemes: false,
    borderColor: "var(--tech)"
  },
  {
    id: 42,
    name: "Пом. 42",
    type: "Коридор",
    area: 4.8,
    lightGroup: "Гр.О3-11 (совм.)",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (1 шт.)",
    hasSchemes: false
  },
  {
    id: 43,
    name: "Пом. 43",
    type: "Аппаратная",
    area: 18.3,
    socketType: "Встроенные IP20, 16А (h=0,3-1,0м) (2-3 шт.)",
    lightFixtures: "BEST ЖКХ-С 10 IP65 (2 шт.)",
    note: "⚠️ Монтаж светильников строго ПОСЛЕ установки венткоробов и труб. Прокладка открыто в ПВХ-трубах.",
    hasSchemes: false,
    borderColor: "var(--tech)"
  }
];